import level.levels, sqlite3, data

def choiceLevel(num, userid):
    conn = sqlite3.connect('users.db')
    dataGame = data.data(userid).dataUser()
    if dataGame[7] == 0:
        if num == 1:
            cur = conn.cursor()
            cur.execute(f"""Update game set target = 50000 where userid = {userid}""")
            cur.execute(f"""Update game set costs = 4000 where userid = {userid}""")
            cur.execute(f"""Update game set income = 5000 where userid = {userid}""")
            cur.execute(f"""Update game set moves = 35 where userid = {userid}""")
            conn.commit()
            cur.close()
            print(1)
            return level.levels.Level(35, 5000, 4000, 50000, userid)
        elif num == 2:
            cur = conn.cursor()
            cur.execute(f"""Update game set target = 60000 where userid = {userid}""")
            cur.execute(f"""Update game set costs = 4400 where userid = {userid}""")
            cur.execute(f"""Update game set income = 5500 where userid = {userid}""")
            cur.execute(f"""Update game set moves = 36 where userid = {userid}""")
            conn.commit()
            cur.close()
            return level.levels.Level(36, 5500, 4400, 60000, userid)
        elif num == 3:
            cur = conn.cursor()
            cur.execute(f"""Update game set target = 70000 where userid = {userid}""")
            cur.execute(f"""Update game set costs = 4800 where userid = {userid}""")
            cur.execute(f"""Update game set income = 6000 where userid = {userid}""")
            cur.execute(f"""Update game set moves = 32 where userid = {userid}""")
            conn.commit()
            cur.close()
            return level.levels.Level(32, 6000, 4800, 70000, userid)
        elif num == 4:
            cur = conn.cursor()
            cur.execute(f"""Update game set target = 80000 where userid = {userid}""")
            cur.execute(f"""Update game set costs = 5200 where userid = {userid}""")
            cur.execute(f"""Update game set income = 6500 where userid = {userid}""")
            cur.execute(f"""Update game set moves = 35 where userid = {userid}""")
            conn.commit()
            cur.close()
            return level.levels.Level(35, 6500, 5200, 80000, userid)
        elif num == 5:
            cur = conn.cursor()
            cur.execute(f"""Update game set target = 90000 where userid = {userid}""")
            cur.execute(f"""Update game set costs = 5600 where userid = {userid}""")
            cur.execute(f"""Update game set income = 7000 where userid = {userid}""")
            cur.execute(f"""Update game set moves = 35 where userid = {userid}""")
            conn.commit()
            cur.close()
            return level.levels.Level(35, 7000, 5600, 90000, userid)
        elif num == 6:
            cur = conn.cursor()
            cur.execute(f"""Update game set target = 100000 where userid = {userid}""")
            cur.execute(f"""Update game set costs = 6000 where userid = {userid}""")
            cur.execute(f"""Update game set income = 7500 where userid = {userid}""")
            cur.execute(f"""Update game set moves = 35 where userid = {userid}""")
            conn.commit()
            cur.close()
            return level.levels.Level(35, 7500, 6000, 100000, userid)
        elif num == 7:
            cur = conn.cursor()
            cur.execute(f"""Update game set target = 120000 where userid = {userid}""")
            cur.execute(f"""Update game set costs = 6400 where userid = {userid}""")
            cur.execute(f"""Update game set income = 8000 where userid = {userid}""")
            cur.execute(f"""Update game set moves = 34 where userid = {userid}""")
            conn.commit()
            cur.close()
            return level.levels.Level(34, 8000, 6400, 120000, userid)
        elif num == 8:
            cur = conn.cursor()
            cur.execute(f"""Update game set target = 140000 where userid = {userid}""")
            cur.execute(f"""Update game set costs = 6800 where userid = {userid}""")
            cur.execute(f"""Update game set income = 8500 where userid = {userid}""")
            cur.execute(f"""Update game set moves = 35 where userid = {userid}""")
            conn.commit()
            cur.close()
            return level.levels.Level(35, 8500, 6800, 140000, userid)
        elif num == 9:
            cur = conn.cursor()
            cur.execute(f"""Update game set target = 160000 where userid = {userid}""")
            cur.execute(f"""Update game set costs = 7200 where userid = {userid}""")
            cur.execute(f"""Update game set income = 9000 where userid = {userid}""")
            cur.execute(f"""Update game set moves = 36 where userid = {userid}""")
            conn.commit()
            cur.close()
            return level.levels.Level(36, 9000, 7200, 160000, userid)
        elif num == 10:
            cur = conn.cursor()
            cur.execute(f"""Update game set target = 180000 where userid = {userid}""")
            cur.execute(f"""Update game set costs = 7600 where userid = {userid}""")
            cur.execute(f"""Update game set income = 9500 where userid = {userid}""")
            cur.execute(f"""Update game set moves = 40 where userid = {userid}""")
            conn.commit()
            cur.close()
            return level.levels.Level(40, 9500, 7600, 180000, userid)
        elif num == 11:
            cur = conn.cursor()
            cur.execute(f"""Update game set target = 200000 where userid = {userid}""")
            cur.execute(f"""Update game set costs = 8000 where userid = {userid}""")
            cur.execute(f"""Update game set income = 10000 where userid = {userid}""")
            cur.execute(f"""Update game set moves = 45 where userid = {userid}""")
            conn.commit()
            cur.close()
            return level.levels.Level(45, 10000, 8000, 200000, userid)
        elif num == 12:
            cur = conn.cursor()
            cur.execute(f"""Update game set target = 225000 where userid = {userid}""")
            cur.execute(f"""Update game set costs = 8800 where userid = {userid}""")
            cur.execute(f"""Update game set income = 11000 where userid = {userid}""")
            cur.execute(f"""Update game set moves = 40 where userid = {userid}""")
            conn.commit()
            cur.close()
            return level.levels.Level(40, 11000, 8800, 225000, userid)
        elif num == 13:
            cur = conn.cursor()
            cur.execute(f"""Update game set target = 250000 where userid = {userid}""")
            cur.execute(f"""Update game set costs = 9600 where userid = {userid}""")
            cur.execute(f"""Update game set income = 12000 where userid = {userid}""")
            cur.execute(f"""Update game set moves = 35 where userid = {userid}""")
            conn.commit()
            cur.close()
            return level.levels.Level(35, 12000, 9600, 250000, userid)
        elif num == 14:
            cur = conn.cursor()
            cur.execute(f"""Update game set target = 275000 where userid = {userid}""")
            cur.execute(f"""Update game set costs = 10400 where userid = {userid}""")
            cur.execute(f"""Update game set income = 13000 where userid = {userid}""")
            cur.execute(f"""Update game set moves = 35 where userid = {userid}""")
            conn.commit()
            cur.close()
            return level.levels.Level(35, 13000, 10400, 275000, userid)
        elif num == 15:
            cur = conn.cursor()
            cur.execute(f"""Update game set target = 300000 where userid = {userid}""")
            cur.execute(f"""Update game set costs = 11200 where userid = {userid}""")
            cur.execute(f"""Update game set income = 14000 where userid = {userid}""")
            cur.execute(f"""Update game set moves = 33 where userid = {userid}""")
            conn.commit()
            cur.close()
            return level.levels.Level(33, 14000, 11200, 300000, userid)
        elif num == 16:
            cur = conn.cursor()
            cur.execute(f"""Update game set target = 350000 where userid = {userid}""")
            cur.execute(f"""Update game set costs = 12000 where userid = {userid}""")
            cur.execute(f"""Update game set income = 15000 where userid = {userid}""")
            cur.execute(f"""Update game set moves = 40 where userid = {userid}""")
            conn.commit()
            cur.close()
            return level.levels.Level(40, 15000, 12000, 350000, userid)
        elif num == 17:
            cur = conn.cursor()
            cur.execute(f"""Update game set target = 400000 where userid = {userid}""")
            cur.execute(f"""Update game set costs = 12800 where userid = {userid}""")
            cur.execute(f"""Update game set income = 16000 where userid = {userid}""")
            cur.execute(f"""Update game set moves = 42 where userid = {userid}""")
            conn.commit()
            cur.close()
            return level.levels.Level(42, 16000, 12800, 400000, userid)
        elif num == 18:
            cur = conn.cursor()
            cur.execute(f"""Update game set target = 450000 where userid = {userid}""")
            cur.execute(f"""Update game set costs = 13600 where userid = {userid}""")
            cur.execute(f"""Update game set income = 17000 where userid = {userid}""")
            cur.execute(f"""Update game set moves = 32 where userid = {userid}""")
            conn.commit()
            cur.close()
            return level.levels.Level(32, 17000, 13600, 450000, userid)
        elif num == 19:
            cur = conn.cursor()
            cur.execute(f"""Update game set target = 500000 where userid = {userid}""")
            cur.execute(f"""Update game set costs = 14400 where userid = {userid}""")
            cur.execute(f"""Update game set income = 18000 where userid = {userid}""")
            cur.execute(f"""Update game set moves = 42 where userid = {userid}""")
            conn.commit()
            cur.close()
            return level.levels.Level(42, 18000, 14400, 500000, userid)
        elif num == 20:
            cur = conn.cursor()
            cur.execute(f"""Update game set target = 550000 where userid = {userid}""")
            cur.execute(f"""Update game set costs = 15200 where userid = {userid}""")
            cur.execute(f"""Update game set income = 19000 where userid = {userid}""")
            cur.execute(f"""Update game set moves = 42 where userid = {userid}""")
            conn.commit()
            cur.close()
            return level.levels.Level(42, 19000, 15200, 550000, userid)
        elif num == 21:
            cur = conn.cursor()
            cur.execute(f"""Update game set target = 600000 where userid = {userid}""")
            cur.execute(f"""Update game set costs = 16000 where userid = {userid}""")
            cur.execute(f"""Update game set income = 20000 where userid = {userid}""")
            cur.execute(f"""Update game set moves = 40 where userid = {userid}""")
            conn.commit()
            cur.close()
            return level.levels.Level(40, 20000, 16000, 600000, userid)
        elif num == 22:
            cur = conn.cursor()
            cur.execute(f"""Update game set target = 650000 where userid = {userid}""")
            cur.execute(f"""Update game set costs = 17600 where userid = {userid}""")
            cur.execute(f"""Update game set income = 22000 where userid = {userid}""")
            cur.execute(f"""Update game set moves = 40 where userid = {userid}""")
            conn.commit()
            cur.close()
            return level.levels.Level(40, 22000, 17600, 650000, userid)
        elif num == 23:
            cur = conn.cursor()
            cur.execute(f"""Update game set target = 700000 where userid = {userid}""")
            cur.execute(f"""Update game set costs = 20000 where userid = {userid}""")
            cur.execute(f"""Update game set income = 25000 where userid = {userid}""")
            cur.execute(f"""Update game set moves = 34 where userid = {userid}""")
            conn.commit()
            cur.close()
            return level.levels.Level(34, 25000, 20000, 700000, userid)
        elif num == 24:
            cur = conn.cursor()
            cur.execute(f"""Update game set target = 750000 where userid = {userid}""")
            cur.execute(f"""Update game set costs = 20000 where userid = {userid}""")
            cur.execute(f"""Update game set income = 25000 where userid = {userid}""")
            cur.execute(f"""Update game set moves = 42 where userid = {userid}""")
            conn.commit()
            cur.close()
            return level.levels.Level(42, 25000, 20000, 750000, userid)
        elif num == 25:
            cur = conn.cursor()
            cur.execute(f"""Update game set target = 800000 where userid = {userid}""")
            cur.execute(f"""Update game set costs = 22400 where userid = {userid}""")
            cur.execute(f"""Update game set income = 28000 where userid = {userid}""")
            cur.execute(f"""Update game set moves = 33 where userid = {userid}""")
            conn.commit()
            cur.close()
            return level.levels.Level(33, 28000, 22400, 800000, userid)
        elif num == 26:
            cur = conn.cursor()
            cur.execute(f"""Update game set target = 850000 where userid = {userid}""")
            cur.execute(f"""Update game set costs = 24000 where userid = {userid}""")
            cur.execute(f"""Update game set income = 30000 where userid = {userid}""")
            cur.execute(f"""Update game set moves = 42 where userid = {userid}""")
            conn.commit()
            cur.close()
            return level.levels.Level(42, 30000, 24000, 850000, userid)
        elif num == 27:
            cur = conn.cursor()
            cur.execute(f"""Update game set target = 900000 where userid = {userid}""")
            cur.execute(f"""Update game set costs = 26400 where userid = {userid}""")
            cur.execute(f"""Update game set income = 33000 where userid = {userid}""")
            cur.execute(f"""Update game set moves = 40 where userid = {userid}""")
            conn.commit()
            cur.close()
            return level.levels.Level(40, 33000, 26400, 900000, userid)
        elif num == 28:
            cur = conn.cursor()
            cur.execute(f"""Update game set target = 950000 where userid = {userid}""")
            cur.execute(f"""Update game set costs = 28800 where userid = {userid}""")
            cur.execute(f"""Update game set income = 36000 where userid = {userid}""")
            cur.execute(f"""Update game set moves = 38 where userid = {userid}""")
            conn.commit()
            cur.close()
            return level.levels.Level(38, 36000, 28800, 950000, userid)
        elif num == 29:
            cur = conn.cursor()
            cur.execute(f"""Update game set target = 1000000 where userid = {userid}""")
            cur.execute(f"""Update game set costs = 31200 where userid = {userid}""")
            cur.execute(f"""Update game set income = 39000 where userid = {userid}""")
            cur.execute(f"""Update game set moves = 32 where userid = {userid}""")
            conn.commit()
            cur.close()
            return level.levels.Level(32, 39000, 31200, 1000000, userid)
        elif num == 30:
            cur = conn.cursor()
            cur.execute(f"""Update game set target = 1100000 where userid = {userid}""")
            cur.execute(f"""Update game set costs = 32000 where userid = {userid}""")
            cur.execute(f"""Update game set income = 40000 where userid = {userid}""")
            cur.execute(f"""Update game set moves = 42 where userid = {userid}""")
            conn.commit()
            cur.close()
            return level.levels.Level(42, 40000, 32000, 1100000, userid)
    else:
        if num == 1:
            return level.levels.Level(35, 5000, 4000, 50000, userid)
        elif num == 2:
            return level.levels.Level(36, 5500, 4400, 60000, userid)
        elif num == 3:
            return level.levels.Level(32, 6000, 4800, 70000, userid)
        elif num == 4:
            return level.levels.Level(35, 6500, 5200, 80000, userid)
        elif num == 5:
            return level.levels.Level(35, 7000, 5600, 90000, userid)
        elif num == 6:
            return level.levels.Level(35, 7500, 6000, 100000, userid)
        elif num == 7:
            return level.levels.Level(34, 8000, 6400, 120000, userid)
        elif num == 8:
            return level.levels.Level(35, 8500, 6800, 140000, userid)
        elif num == 9:
            return level.levels.Level(36, 9000, 7200, 160000, userid)
        elif num == 10:
            return level.levels.Level(40, 9500, 7600, 180000, userid)
        elif num == 11:
            return level.levels.Level(45, 10000, 8000, 200000, userid)
        elif num == 12:
            return level.levels.Level(40, 11000, 8800, 225000, userid)
        elif num == 13:
            return level.levels.Level(35, 12000, 9600, 250000, userid)
        elif num == 14:
            return level.levels.Level(35, 13000, 10400, 275000, userid)
        elif num == 15:
            return level.levels.Level(33, 14000, 11200, 300000, userid)
        elif num == 16:
            return level.levels.Level(40, 15000, 12000, 350000, userid)
        elif num == 17:
            return level.levels.Level(42, 16000, 12800, 400000, userid)
        elif num == 18:
            return level.levels.Level(32, 17000, 13600, 450000, userid)
        elif num == 19:
            return level.levels.Level(42, 18000, 14400, 500000, userid)
        elif num == 20:
            return level.levels.Level(42, 19000, 15200, 550000, userid)
        elif num == 21:
            return level.levels.Level(40, 20000, 16000, 600000, userid)
        elif num == 22:
            return level.levels.Level(40, 22000, 17600, 650000, userid)
        elif num == 23:
            return level.levels.Level(34, 25000, 20000, 700000, userid)
        elif num == 24:
            return level.levels.Level(42, 25000, 20000, 750000, userid)
        elif num == 25:
            return level.levels.Level(33, 28000, 22400, 800000, userid)
        elif num == 26:
            return level.levels.Level(42, 30000, 24000, 850000, userid)
        elif num == 27:
            return level.levels.Level(40, 33000, 26400, 900000, userid)
        elif num == 28:
            return level.levels.Level(38, 36000, 28800, 950000, userid)
        elif num == 29:
            return level.levels.Level(32, 39000, 31200, 1000000, userid)
        elif num == 30:
            return level.levels.Level(42, 40000, 32000, 1100000, userid)